version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: toollistinsights-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      # Environment parameters for TCP connection to MS SQL Server
      - DB_D4_SERVER=srvdms\D4
      - DB_D4_DATABASE=D4
      - DB_D4_USER=werkzeug
      - DB_D4_PASSWORD=werkzeug
      - DB_D4_ENCRYPT=false

      - DB_WT_SERVER=srvdaten\cim4net
      - DB_WT_DATABASE=WTData
      - DB_WT_USER=werkzeug
      - DB_WT_PASSWORD=werkzeug
      - DB_WT_ENCRYPT=false
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE=/api
    container_name: toollistinsights-frontend
    ports:
      - "2005:80"
    depends_on:
      - backend
    restart: always
